name: Terraform
on: [push]
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
      - run: npm run setup
      - name: Upload dependencies
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules
  Test-Node-Dependencies:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
      - name: Download dependencies
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules
      - run: npm run test:node:audit
  Test-Node-Linting:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
      - name: Download dependencies
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules
      - run: npm run test:node:lint
