name: Terraform
on: [push]
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
      - run: npm run setup:production
