name: Quality Assurance
on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  CI_GITHUB: 1
  TF_VAR_aws_account_id: ${{vars.TF_VAR_AWS_ACCOUNT_ID}}
  TF_VAR_environment: github-${{github.ref_name}}
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
      - run: npm run setup
      - name: Cache dependencies
        uses: actions/cache/save@v3
        with:
          key: node_modules-${{github.sha}}
          path: node_modules
  Test-Node-Dependencies:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
      - name: Download dependencies
        uses: actions/cache/restore@v3
        with:
          key: node_modules-${{github.sha}}
          path: node_modules
      - run: npm run test:node:audit
  Test-Node-Linting:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
      - name: Download dependencies
        uses: actions/cache/restore@v3
        with:
          key: node_modules-${{github.sha}}
          path: node_modules
      - run: npm run test:node:lint
  Test-Terraform-Linting:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Install Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: latest
          token: ${{secrets.GITHUB_TOKEN}}
      - run: npm run test:terraform:lint
  Plan:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Install Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: latest
          token: ${{secrets.GITHUB_TOKEN}}
      - run: npm run plan
  Deploy:
    runs-on: ubuntu-latest
    needs: Plan
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Install Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: latest
          token: ${{secrets.GITHUB_TOKEN}}
      - run: npm run apply
  Undeploy:
    runs-on: ubuntu-latest
    needs: Deploy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Install Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: latest
          token: ${{secrets.GITHUB_TOKEN}}
      - run: npm run destroy
